#!/usr/bin/python   
# -*- coding: utf-8 -*-  
  

def twitter_login():  
      
    import twitter  
      
    CONSUMER_KEY = 'qcdOvcImDyi3wlojLpQ7FTyTh'  
    CONSUMER_SECRET = 'YUpHMMbXsN5pp3uIqeuzVxzvyF2YGRrJbgAt1kWqGxI1wW9hWm'  
    OAUTH_TOKEN = '851203778569056256-Pn9Pp4kXXOxmzDacX6DleAKthR5264t'  
    OAUTH_TOKEN_SECRET = 'tzERYHZKC920PfYhq8LherIOREi1y3OMplcMZYEPkltQu'  
      
    auth = twitter.oauth.OAuth(OAUTH_TOKEN, OAUTH_TOKEN_SECRET,  
                                CONSUMER_KEY, CONSUMER_SECRET)  
      
    twitter_api = twitter.Twitter(auth=auth)  
    return twitter_api  
